//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineDelivery.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;

	public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.tblCoins = new HashSet<tblCoin>();
        }
    
        public int CustomerID { get; set; }
		
		public string CustomerName { get; set; }
		[DataType(DataType.EmailAddress)]
		[Required]
		[DisplayName("Email")]
        public string CustomerEmail { get; set; }
		[DisplayName("Address")]
		public string CustomerAddress { get; set; }
		[DataType(DataType.Password)]
		[Required]
		[DisplayName("Password")]
		public string CustomerPassword { get; set; }
		[DisplayName("Gender")]
		public string CustomerGender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCoin> tblCoins { get; set; }
    }
}
