//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineDelivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSub
    {
        public int OrderSub_ID { get; set; }
        public Nullable<int> OrderMain_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Total_price { get; set; }
    
        public virtual OrderMain OrderMain { get; set; }
        public virtual Productiteam Productiteam { get; set; }
    }
}
