//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineDelivery.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;

	public partial class Shopkeeper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shopkeeper()
        {
            this.OrderMains = new HashSet<OrderMain>();
        }
    
        public int Shopkeeper_ID { get; set; }
		[Required]
		[DisplayName("Name")]
		public string Shopkeeper_Name { get; set; }
		[Required]
		[DisplayName("Phone")]
		[DataType(DataType.PhoneNumber)]
		public Nullable<int> Shopkeeper_Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMain> OrderMains { get; set; }
    }
}
