//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineDelivery.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;

	public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.OrderMains = new HashSet<OrderMain>();
        }
    
        public int Supplier_ID { get; set; }
		[Required]
		[DisplayName("Supplier Name")]
		public string Supplier_Name { get; set; }

		[Required]
		[DisplayName("Supplier Area")]
		public string Supplier_Area { get; set; }

		[Required]
		[DisplayName("Supplier Phone")]
		[DataType(DataType.PhoneNumber)]
		public Nullable<int> Supplier_Phone { get; set; }

		[Required]
		[DisplayName("Password")]
		[DataType(DataType.Password)]
		public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMain> OrderMains { get; set; }
    }
}
